# Generated by Django 4.2.7 on 2025-07-30 13:24

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Business Categories",
            },
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("spaza_shop", "Spaza Shop"),
                            ("restaurant", "Restaurant"),
                            ("electronics", "Electronics"),
                            ("fashion", "Fashion & Beauty"),
                            ("services", "Services"),
                            ("grocery", "Grocery Store"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("whatsapp_number", models.CharField(blank=True, max_length=15)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("registration_number", models.CharField(blank=True, max_length=50)),
                ("tax_number", models.CharField(blank=True, max_length=50)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("opens_at", models.TimeField(blank=True, null=True)),
                ("closes_at", models.TimeField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="business_logos/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="business_covers/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="businesses.businesscategory",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Businesses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="businesses__slug_9e86f6_idx"),
                    models.Index(
                        fields=["category"], name="businesses__categor_908071_idx"
                    ),
                    models.Index(
                        fields=["business_type"], name="businesses__busines_cfa4f0_idx"
                    ),
                    models.Index(fields=["city"], name="businesses__city_0894c6_idx"),
                    models.Index(
                        fields=["province"], name="businesses__provinc_d45208_idx"
                    ),
                    models.Index(
                        fields=["owner"], name="businesses__owner_i_7abb69_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="businesses__is_acti_e70536_idx"
                    ),
                    models.Index(
                        fields=["is_featured"], name="businesses__is_feat_be1c9d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="businesses__created_34b472_idx"
                    ),
                ],
            },
        ),
    ]
